### PR TITLE
Hook up vectors of Points and vectors of those to GeoInterface

### PR DESCRIPTION
**Pull request by asinghvi17**
Vector{Point} is a LineString
Vector{Vector{Point}} is a MultiLineString

Need this for the generic datashader thing :)

### CODE REVIEW

**Comment by rafaqz** [comment]
Isn't it ambiguous what a vector of points is though? It could be a MultiPoint or a LineString or a LinearRing...

Why not just wrap them before use?

**Comment by SimonDanisch** [comment]
If we implement the bin counting with OpenGL, we could just use all of the normal rendering pipeline

**Comment by rafaqz** [comment]
Also this is directly clashing with my other PR... I was removing vectors completely as geometries :sweat_smile:

**Comment by SimonDanisch** [comment]
I guess we can close this?

**Comment by asinghvi17** [comment]
Yeah I think so

**Pull request closed without merging**
