### PR TITLE
Improve tests and minor fixes

### PR DESCRIPTION
**Pull request by Sov-trotter**

### CODE REVIEW

**Comment by Sov-trotter** [comment]
Fixes #45

**Comment by goretkin** [comment]
The `GeometryBasics` qualification on `value` really should not be needed. I just cloned the branch `Sov-trotter:tests_improv`, removed the qualification, and all the tests (including the new ones written, woohoo) pass.

xref: https://github.com/JuliaGeometry/GeometryTypes.jl/pull/187/files 

Can you see if you're still getting the issue in #45 after removing the qualification? If you are, then please provide a reproducing example.

This does not produce the error:
```julia
import GeometryBaics: OffsetInteger
OffsetInteger{0}(1) + OffsetInteger{0}(1)
```

**Comment by Sov-trotter** [comment]
I guess I was running it in REPL so the error ?

**Comment by SimonDanisch** [comment]
Thanks!

**Pull request merged**
