### PR TITLE
remove LineP

### PR DESCRIPTION
**Pull request by visr**
See discussion in #10.
Does this have any downsides?
I tried to take the `V` out of `LineString` as well, but was not sure how to do that without restricting it's field to what was `V`. Or is there no need to restrict that field, since it is already taken care of by the subtyping? Am a bit confused.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
We should probably also have tests for type stability to see that we don't have any regressions!

**Comment by visr** [comment]
Yeah how do we easily check that?

**Comment by asinghvi17** [comment]
`@inferred` perhaps?

**Comment by SimonDanisch** [comment]
Hm so parts of me like this, to reduce complexity & compilation times (possibly?), and another part thinks, oh no, now this is not strictly typed anymore :-O

**Comment by visr** [comment]
Yeah I think I understand. I'll close the PR. Feel free to reopen if you still want to consider it more.

**Pull request closed without merging**
