### PR TITLE
Prototype docs

### PR DESCRIPTION
**Pull request by asinghvi17**
Builds on the `sd/finish` branch.  Adds a couple of documentation pages with not much on there yet.

cc: @Tokazama

### CODE REVIEW

**Comment by Tokazama** [comment]
Should I start transferring relevant docs from GeometryTypes here or is this just going to be a good placeholder for documentation for the time being?

**Comment by asinghvi17** [comment]
I think transferring the documentation here would be worthwhile, I'll make you a collaborator in my fork.  It should probably be reworked, though!

**Comment by Tokazama** [comment]
Why do we have `contains` if it is exactly equivalent to `in`?

**Comment by asinghvi17** [comment]
I would guess it's meant to avoid piracy, but am not sure.

**Comment by asinghvi17** [comment]
@SimonDanisch should this be merged?

**Comment by SimonDanisch** [comment]
Yes thank you :)

**Pull request merged**
