### PR TITLE
Fix #168

### LINKED ISSUE #168: Bug in Line Intersection ( GeometryBasics.intersects )
I found a pair of lines that `GeometryBasics.intersects` claims don't intersect even though they do.  How to reproduce:

I'm using `Julia 1.7.2` with `[5c1252a2] GeometryBasics v0.4.1`

If you run the following code
```
using GeometryBasics
const GB = GeometryBasics
mkline(pair) = GB.Line(GB.Point(pair[1]...), GB.Point(pair[2]...))
bug2 =(mkline([-3.1, 15.588457268119894] => [3.1, 15.588457268119894]),
    mkline([2.0866025403784354, 17.37050807568877] => [-4.0866025403784505, 13.806406460551015]))
GB.intersects(bug2[1], bug2[2])
```
I get `(false, [0.0, 0.0])` even though these lines should intersect.  To confirm that they do I've drawn the lines using the `Luxor` package here: https://imgur.com/a/3sADDln

Drawing code for ease of copy paste:
```
using Luxor
@draw begin
    LP = Luxor.Point
    dscale=10
    setline(1)
    sethue("black")
    for (p1, p2) in bug2
        asp(p) = let 
            v = ([dscale, -dscale] .* vec(p))
            @show v
            Luxor.Point(v...)
        end
        line(asp(p1), asp(p2); action=:stroke)
    end
end
```

Anyway, thanks for having made the geometry package, and I'll be curious to see what the bug was.

### PR DESCRIPTION
**Pull request by cmcaine**
Replaces the intersection algorithm with one that seems more reliable.

See here for the algorithm and explanation: http://paulbourke.net/geometry/pointlineplane/

This algorithm is also used in Turf.js, Turf.jl, etc.

I did a bunch of testing with other algorithms and even tested some algorithms from ChatGPT. You can see some of the testing here: https://gist.github.com/cmcaine/80600c1fd32a6ac3822f2fac4ab93367

### CODE REVIEW

**Review by rafaqz — COMMENTED** [review]
This looks good to me. Have you done a benchmark comparison?

**Comment by cmcaine** [comment]
Thanks for the review! I probably benchmarked it at the time but I've forgotten now.

It's a much simpler algorithm and I would be very surprised if it was slower than the existing code.

For me, the more important thing is that this is a well-known and peer-reviewed algorithm and the current implementation is not (perhaps it's a published algorithm, but I'm not familiar with it and it's provenance isn't noted in the code). The Paul Bourke algorithm I've used also seems to give better quality results, as evidenced by the tests I added, etc.

**Comment by cmcaine** [comment]
Oh, there are benchmarks and a bunch of code evaluating the accuracy of various line intersection algorithms in my gist that I linked in my first post.

https://gist.github.com/cmcaine/80600c1fd32a6ac3822f2fac4ab93367

**Comment by rafaqz** [comment]
I mean, posting the `btime` output here is the path to getting this merged, no-one will read your link.

I dont have commit access here.

**Comment by cmcaine** [comment]
I'm not gonna rerun this stuff for a package I don't use any more and a PR that I don't believe is ever going to be merged. 🤷

The short of it is that the algorithm in this PR is better known, better tested, seems to produce better output and (least importantly, imo) is almost certainly faster.

Simon can take it or leave it. I appreciate that they're spread thin.

**Comment by rafaqz** [comment]
No worries! I use GeometryOps.jl for this ;)

It would just be good to not have correctness issues around and proving inline in comments that a PR is all upside no downside is a pretty reliable way to get it merged by people with zero spare time.

**Comment by SimonDanisch** [comment]
Thank you @cmcaine and sorry for taking so long. I'm not familiar with line intersection algorithm and have little time for review.
Thanks everyone for sanity checking this, I'm not familiar with line intersection algorithms, so having a few more eyes on this helps a lot to actually merge it.

**Comment by cmcaine** [comment]
Thanks knuesel!

Thanks very much Simon for your work on this package (which I maybe use indirectly?) and on many other packages that I and others benefit from 💜.

I lost a few hours to this bug and in writing the PR, but you've saved me many more than that over the years :D

**Pull request merged**
