### PR TITLE
Replace f0 type suffix with f, rename Rect types

### PR DESCRIPTION
**Pull request by knuesel**
This implements the change proposed in https://github.com/JuliaGeometry/GeometryBasics.jl/issues/61 . If the GeometryBasics maintainers are OK with this, I'll make PRs for all the dependents.

### CODE REVIEW

**Comment by juliohm** [comment]
We are trying to clean up the whole `Vecf`, `Pointf` story. The refactoring of the code is taking place in the `cleaned` branch.

**Comment by SimonDanisch** [comment]
>I'll make PRs for all the dependents.

That'd be amazing :-0

**Comment by SimonDanisch** [comment]
We should also properly deprecate the old names!

**Comment by knuesel** [comment]
I hadn't followed the developments on the `cleanup` branch, which look like a more ambitious refactoring. I'll post some ideas in #100.

@SimonDanisch indeed, proper deprecation was not (yet) in my PR. It's not clear though if it makes sense to keep this one, with the other changes going on in `cleanup`.

**Comment by SimonDanisch** [comment]
>It's not clear though if it makes sense to keep this one, with the other changes going on in cleanup.

Cleanup is a much larger project, this one could be merged fairly quickly if you can open those PRs & we deprecate the old binding correctly ;)

**Comment by knuesel** [comment]
Hi, I have some time in the coming days to finish this 🙂 I've rebased the PR on master and added deprecation warnings for the old types.

There's a corresponding Makie PR at https://github.com/JuliaPlots/Makie.jl/pull/1132.

While we are at it, I propose to add the following renames to this PR:

`Rect2D`, `Rect3D` -> `Rect2`, `Rect3` 
`FRect`, `FRect2D`, `FRect3D` -> `Rectf`, `Rect2f`, `Rect3f` 
`IRect`, `IRect2D`, `IRect3D` -> `Recti`, `Rect2i`, `Rect3i`
`TRect` -> `RectT`

This is for internal consistency and is also easier to type, and consistent with what some other libraries do (see e.g. https://docs.opencv.org/3.4/dc/d84/group__core__basic.html).

What do you think?

**Comment by knuesel** [comment]
@SimonDanisch I have added the Rect renames with deprecation warnings. For me this PR is ready.

**Comment by SimonDanisch** [comment]
Awesome thank you!

**Comment by knuesel** [comment]
You're welcome! I've made the PRs to the closely related projects I could find. For other (third-party) projects I think it makes more sense to wait for new releases of GeometryBasics and Makie, so I can make PRs that work with the new versions.

Let me know if there's anything else to do to get this merged!

**Comment by SimonDanisch** [comment]
Thank you for all the effort! Lets merge this!

**Comment by knuesel** [comment]
@SimonDanisch was the 0.4.0 release supposed to include this?

**Comment by SimonDanisch** [comment]
Lol, what happened here :-O Yeah, definitely 😅

**Pull request merged**
