### PR TITLE
Doc fixes

### LINKED ISSUE #119: Documentation is broken
The [documentation page](https://juliageometry.github.io/GeometryBasics.jl/dev/primitives/) currently contains nothing but “Missing docstring” messages. I can also replicate this in a downloaded version of the package, and can't access any documentation from inside the REPL either.

### LINKED ISSUE #128: Fix docs warnings
there are some warnings about missing docs or duplicated docstrings, see eg. [here](https://github.com/JuliaGeometry/GeometryBasics.jl/runs/1749392970#step:5:41)

### PR DESCRIPTION
**Pull request by knuesel**
* Remove mention of distance fields (there's nothing about them in the code)
* Fix the duplicate references
* Convert the quickstart example to doc `@repl` blocks (and add a mention of `GeometryBasics.mesh`)
* Add CI doc step, calling `doctest()` so an error is reported if doctests fail

Feel free to squash the commits before merging...

Fixes #119, fixes #128

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Lovely :)

**Comment by knuesel** [comment]
Forgot to mention: there are two links in `primitives.md` that I converted to link-less text because no docstring exist for them:

```
GeometryPrimitive
AbstractSimplex
```

I thought I'd let someone competent add docstrings for these...

**Comment by mforets** [comment]
Bump? Nice work @knuesel ! Thanks for fixing the build warnings from the issue I opened last week (#128).
About the remaining issue, I assume they can be added in subsequent PRs ;)

**Comment by hyrodium** [comment]
Thanks! I'm really looking forward to this PR being merged!

@knuesel
Could you resolve the conflicts of README.md?
I think we can't use `@repl` block in `README.md` because that is for GitHub repository page.
We have two options:
* Remove most of contents from `README.md`, and replace them with [the link to the document](https://juliageometry.github.io/GeometryBasics.jl/dev/).
* Remove [copying README](https://github.com/JuliaGeometry/GeometryBasics.jl/blob/master/docs/make.jl#L10), and add new page for quick start in the document.

I think the first option is recommended.

**Comment by SimonDanisch** [comment]
Damn totally forgot about this PR! Would be nice to merge it ;) Let me know if I can help with anything!

**Comment by knuesel** [comment]
Thanks for the bump @hyrodium . I separated the README and index.md as suggested:

* The quickstart is now in `index.md` which is its own file (not copied from the README)
* The README links to the documentation and adds information specific to developers (e.g. how to build the documentation)

I also updated the doctests and CI config to expect output from Julia 1.6.

@SimonDanisch for me this is ready to be merged.

**Comment by hyrodium** [comment]
Thanks for the fixes! Nice contribution:tada:

**Comment by knuesel** [comment]
Ah @SimonDanisch one thing you might want to consider: maybe you'd prefer to have `@repl` blocks in `metadata.md`, instead of `jldoctest` blocks which might be annoying to maintain?

See [here](https://github.com/JuliaGeometry/GeometryBasics.jl/pull/129/commits/3becc8db7a8bed43c98198ee9e7f007036942321#diff-9b910e73210227377d54e7c143f9e1ba551ed7857384e23fba3a30c19a26ec80) for the changes I had to make for Julia 1.6. It was quick to do with `doctest(GeometryBasics, fix=true)` but it adds some friction.

On the other hand you might prefer to keep the jldoctests to check that things behave as expected?

**Comment by knuesel** [comment]
I went ahead and converted the jldoctests to `@repl` blocks (easier to maintain).

@SimonDanisch I think we're good?

**Comment by SimonDanisch** [comment]
Cool, thanks a lot! :)

**Pull request merged**
